services:
  lock-generator:
    image: python:3.12-slim
    volumes:
      - .:/app/
    working_dir: /app
    command: >
      /bin/sh -c "pip install -r requirements.txt &&
                  pip freeze > requirements.lock.txt"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  tf2-express:
    image: tf2-express-image
    container_name: tf2-express
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
    volumes:
      - .:/app
    working_dir: /app
    command: python3 main.py
    ports:
      - "5000:5000"

volumes:
  mongo_data: